### ISSUE TITLE
Document css class usage

### ISSUE THREAD

**Issue by maxkfranz** [iVis-at-Bilkent/cytoscape.js-context-menus#15]
There's already a great example stylesheet in the repo: https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus/blob/master/cytoscape-context-menus.css

It would be good to have explicit descriptions of each class name in the readme.

**Comment by metincansiper** [comment]
@maxkfranz we have not documented them because the users are already able to customize the context menu itself and the menu items using ```menuItemClasses``` and ```contextMenuClasses``` options. Each context menu (one per each cytoscape.js instance where this extension is registered) has classes specified by ```contextMenuClasses``` along with  ```cy-context-menus-cxt-menu```. Each context menu item has classes specified by ```menuItemClasses``` along with ```cy-context-menus-cxt-menuitem```. 

One downside of specifying that classes may be that, if we specify them in README then modifying them will become an API change and we will need to make a major release when we need to modify them. As we already provide customization for this, I think that we can keep avoiding documenting these classes. What do you thinkl about this? Do you think which way is more preferable to go?

Also, I realized that in README we did not mention that the users should include that css file while using this extension. I think that specifing it would be nice.

**Comment by maxkfranz** [comment]
OK.

If the user is expected to include the default stylesheet, then we should probably point the `style` field of `package.json` to the css file so it's more automatic.

**Comment by metincansiper** [comment]
@maxkfranz I added that field to ```package.json```. Would you close the issue if there is no problem?
